# -*- coding: utf-8 -*-
"""Tracksheetautomation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FO0hiplit6DHKxUVo1gtqGH-S_X_45yl
"""

pip install gspread pandas google-auth

from google.colab import files
uploaded = files.upload("finance-tracksheet-9c569a71dbac.json")

from google.oauth2.service_account import Credentials
import gspread
import pandas as pd

scope = ["https://www.googleapis.com/auth/spreadsheets"]
creds = Credentials.from_service_account_file("finance-tracksheet-9c569a71dbac.json/finance-tracksheet-9c569a71dbac.json", scopes=scope)

client = gspread.authorize(creds)

sheet = client.open_by_key("1Mzybgh1NZ6jOrQHCzmA4ZZNn2BuImAHV9WAD2s4Dq-8").worksheet("Transactions")

# Get all values from the sheet instead of using get_all_records directly
all_values = sheet.get_all_values()

if not all_values:
    print("Worksheet is empty.")
    df = pd.DataFrame()
else:
    # Find the row that contains the actual headers (e.g., 'Date', 'Amount')
    header_row_index = -1
    for i, row in enumerate(all_values):
        if 'Date' in row and 'Amount' in row and 'Category' in row:
            header_row_index = i
            break

    if header_row_index == -1:
        print("Could not find a suitable header row. Using first row as headers.")
        headers = all_values[0]
        data_rows = all_values[1:]
    else:
        headers = all_values[header_row_index]
        data_rows = all_values[header_row_index + 1:]

    # Clean headers: replace empty strings with unique names, ensure overall uniqueness
    cleaned_headers = []
    # Using a dictionary to track original names and their counts for uniqueness
    header_occurrence_counts = {}
    for i, h in enumerate(headers):
        # Use original header if not empty, otherwise create a generic 'Unnamed_X'
        # header
        base_name = h.strip() if h.strip() else f"Unnamed_{i}"

        # Ensure uniqueness by appending a number if the header already exists
        current_name = base_name
        count = header_occurrence_counts.get(base_name, 0)
        if count > 0:
            current_name = f"{base_name}_{count}"
        header_occurrence_counts[base_name] = count + 1

        # If the generated current_name is still not unique (e.g., due to original
        # 'Unnamed_X' clashes) ensure it becomes unique by incrementing a counter
        # specific to the cleaned_headers list
        final_name = current_name
        duplicate_idx = 1
        while final_name in cleaned_headers:
            final_name = f"{current_name}_{duplicate_idx}"
            duplicate_idx += 1
        cleaned_headers.append(final_name)

    df = pd.DataFrame(data_rows, columns=cleaned_headers)
    # Convert 'Amount' column to numeric, coercing errors to NaN
    if 'Amount' in df.columns:
        df['Amount'] = pd.to_numeric(df['Amount'].astype(str).str.replace(',', ''), errors='coerce')

df.head()

df["Date"] = pd.to_datetime(df["Date"])

# Filter for January 2026 data, as per the available dataset
current_month = df[df["Date"].dt.month == 1]

income = current_month[current_month["Category"] == "Income"]["Amount"].sum()
expenses = current_month[current_month["Category"] == "Expenses"]["Amount"].sum()

savings = current_month[current_month["Segment"] == "Savings"]["Amount"].sum()

top_spending = (
    current_month[current_month["Category"] == "Expenses"] # Filter for expense transactions based on 'Category'
    .groupby("Segment") # Group by 'Segment' to identify top spending areas within expenses
    ["Amount"].sum()
    .sort_values(ascending=False)
)

def generate_smart_insight():
    insight = ""

    if income == 0:
        return "No income recorded this month."

    if expenses > income:
        insight += "⚠️ Your expenses exceed your income. This is not sustainable.\n"
    else:
        insight += "✅ You are spending within your income.\n"

    if savings > 0:
        insight += f"💰 You saved ₦{savings:,.0f} this month.\n"
    else:
        insight += "⚠️ No savings recorded this month.\n"

    # Calculate expense breakdown for top category analysis
    expense_breakdown = (
        current_month[current_month["Category"] == "Expenses"]
        .groupby("Segment")["Amount"]
        .sum()
    )

    if not expense_breakdown.empty:
        top_category = expense_breakdown.idxmax()
        insight += f"📊 Your highest spending was on {top_category}.\n"
        # Recommendation
        insight += "💡 Consider reducing spending in your top category to improve savings."
    else:
        insight += "📊 No specific expense categories found for detailed analysis.\n"
        insight += "💡 Review your expense entries for more detailed categorization to get better insights."

    return insight

def clean_summary(text):
    # Placeholder function: In a real application, this would likely involve calling
    # an AI model to process or summarize the text, and then cleaning its response.
    # For now, it simply returns the text as is.
    return text.strip()

ai_insight = clean_summary(generate_ai_prompt())

html_content = f"""
<h2>📊 Monthly Finance Report</h2>

<p><b>Income:</b> ₦{income:,.0f}</p>
<p><b>Expenses:</b> ₦{expenses:,.0f}</p>
<p><b>Savings:</b> ₦{savings:,.0f}</p>

<h3>📈 Top Spending</h3>
<p>{top_spending.head(3).to_string()}</p>
"""

insight = generate_smart_insight()

html_content += f"""
<div style="background:#f5f7fa; padding:15px; border-radius:8px; margin-top:20px;">
    <h3>Financial Insights</h3>
    <p style="line-height:1.6;">
    {insight.replace('\n', '<br>')}
    </p>
</div>
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from google.colab import userdata # For EMAIL_PASS

# --- User-configurable variables (placeholders) ---
# Sender's email address (should be a Gmail address for the default SMTP settings)
EMAIL = "isaiahakinlabi99@gmail.com"

# It's highly recommended to store sensitive information like passwords in Colab Secrets.
# Go to the 'Secrets' tab (lock icon) in the left panel and add a secret named 'EMAIL_PASS'
# with your app-specific password. If you're using Gmail, you'll need to generate an App Password.
# See: https://support.google.com/accounts/answer/185833?hl=en
EMAIL_PASS = userdata.get('GMAIL_APP_PASSWORD')

# List of recipient email addresses
recipients = ["daprincetech99@gmail.com"] # Replace with actual recipients
# --- End of user-configurable variables ---

# Create the email message container.
msg = MIMEMultipart("alternative")
msg["Subject"] = "Monthly Finance Report"
msg["From"] = EMAIL

# Attach the HTML content to the email.
# 'html_content' is assumed to be defined in a previous cell.
part1 = MIMEText(html_content, "html")
msg.attach(part1)

msg["To"] = ", ".join(recipients)

# Connect to the SMTP server and send the email
try:
    # For Gmail, the SMTP server is smtp.gmail.com and the port is 465 for SSL
    server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
    server.login(EMAIL, EMAIL_PASS)
    server.sendmail(EMAIL, recipients, msg.as_string())
    server.quit()
    print("Email sent successfully!")
except Exception as e:
    print(f"Failed to send email: {e}")